name: Tests
on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10']
        poetry-version: [1.3.1]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4 # get source
        with:
          github-server-url: https://gitea.sheep-ghoul.ts.net

      - name: Install Python 3
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry # dependency management
        uses: abatilo/actions-poetry@v2.1.6
        with:
          poetry-version: ${{ matrix.poetry-version }}

      - name: Install Dependencies
        run: poetry install

      - name: Run Tests # test script
        run: poetry run python -m unittest discover -s tests

  publishLib:
    runs-on: ubuntu-latest
    name: Package Library
    needs: [ build ] # for ignoring bad builds
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          github-server-url: https://gitea.sheep-ghoul.ts.net

      - name: Install Python 3
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry # dependency management
        uses: abatilo/actions-poetry@v2.1.6
        with:
          poetry-version: ${{ matrix.poetry-version }}

      - name: Add SarGit Repo
        run: |
          cat <<EOF > ~/.pypirc
          [distutils]
          index-servers = sargit
          
          [sargit]
          repository = https://git.sarsoo.xyz/api/packages/${{ secrets.PYPI_USERNAME }}/pypi
          username = ${{ secrets.PYPI_USERNAME }}
          password = ${{ secrets.PYPI_KEY }}
          EOF         

      - name: Poetry Build
        run: poetry build

      - name: Poetry Publish
        run: poetry publish